# Configuration for Statistics Importer script

# URL of Home Assistant
ha_url: "localhost:8123"

# Specify if Home Assistant uses SSL or not
ha_use_ssl: false

# Long-Lived access token from Home Assistant
ha_access_token: "xxxxxx"

# Guelph Hydro username
hydro_username: 'xxxxxx'

# Guelph Hydro password
hydro_password: 'xxxxxx'

#InfluxDB access configuration
influx_token: 'xxxx'
influx_url: 'http://localhost:8086'
influx_bucket: 'xxxx' 
influx_org: 'xxxx'

